baseURL: "https://dranidis.gr/"
languageCode: en-us
title: Dimitris Dranidis
theme: PaperMod
author:
  name: Dimitris Dranidis

params:
  env: production
  author: Dimitris Dranidis
  ShowShareButtons: true
  ShareButtons:
    - linkedin
    - twitter
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  hideSummary: false
  hideFooter: false
  profileMode:
    enabled: true
    title: In Wonderland... and beyond
    subtitle: "This is my personal blog. I write about topics that I enjoy, mostly about software engineering, testing and software quality."
    #  imageUrl: <image link>
    # imageTitle: <title of image as alt>
    imageWidth: 120
    imageHeight: 120
  homeInfoParams:
    title: In Wonderland... and beyond
    Content: This is my personal blog. I write about topics that I enjoy, mostly about software engineering, testing and software quality. Read more about me [here](/about).
  socialIcons:
    - name: linkedin
      url: "https://gr.linkedin.com/in/dranidis"
    - name: github
      url: "https://github.com/dranidis"
    - name: twitter
      url: "https://twitter.com/dranidis"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/22857518/dimitris-dranidis"
    - name: "rss"
      url: "https://dranidis.gr/index.xml"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0 # Determines approximately where in the text is the pattern expected to be found.
    distance: 100 # A distance of 100 would require a perfect match to be within 20 characters of the location to be found using a threshold of 0.2
    threshold: 0.3 # At what point does the match algorithm give up. A threshold of 0.0 requires a perfect match (of both letters and location), a threshold of 1.0 would match anything.
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 15
    - identifier: tags
      name: Projects
      url: /projects/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 25
    - identifier: search
      name: Search
      url: /search/
      weight: 30
